name: nsidc_data_cookbook
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - cartopy
 - dask
 - netCDF4
 - bottleneck
 - xarray
 - rioxarray
 - pandas
 - pytest
 
