name: nsidc_data_cookbook
channels:
 - conda-forge
dependencies:
 - python ~=3.13
 ###################################################
 # Imported dependencies and extensions            #
 ###################################################
 - jupyterlab<=4.2
 - matplotlib
 - cartopy
 - dask
 - netCDF4
 - bottleneck
 - xarray
 - rioxarray
 - pandas
 - geopandas
 - pytest
 - earthaccess
 - h5py
 - h5netcdf
 - hvplot
 - geoviews
 - ipyleaflet
 - virtualizarr
 - fsspec
 - pip
 - pip:
    - harmony-py
